name = "hamsoya-backend-dev"
main = "src/index-dev.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

# Development environment
[env.development]
name = "hamsoya-backend-dev"
[env.development.vars]
NODE_ENV = "development"
FRONTEND_URL = "http://localhost:3000"
BACKEND_URL = "http://localhost:8787"

# Default environment variables
[vars]
NODE_ENV = "development"
FRONTEND_URL = "http://localhost:3000"
BACKEND_URL = "http://localhost:8787"

# Limits and performance
[limits]
cpu_ms = 50000
